INSERT INTO `csv_export` (`target`, `field`, `item_order`, `shown`)
VALUES ('reservations', '予約ID', 1, 1),
       ('reservations', 'お名前', 2, 1),
       ('reservations', 'ユーザーID', 3, 1),
       ('reservations', '会員区分', 4, 1),
       ('reservations', 'ユーザー電話番号', 5, 1),
       ('reservations', '性別', 6, 1),
       ('reservations', 'ユーザーEmail', 7, 1),
       ('reservations', 'ご利用人数', 8, 1),
       ('reservations', '利用目的', 9, 1),
       ('reservations', '予約対応', 10, 1),
       ('reservations', 'スペース名', 11, 1),
       ('reservations', 'スペースID', 12, 1),
       ('reservations', '大エリア（都道府県）', 13, 1),
       ('reservations', '中エリア', 14, 1),
       ('reservations', '小エリア', 15, 1),
       ('reservations', 'スペース住所', 16, 1),
       ('reservations', '団体／会社名', 17, 1),
       ('reservations', '団体／会社ID', 18, 1),
       ('reservations', '団体／会社エリア', 19, 1),
       ('reservations', '団体／会社住所', 20, 1),
       ('reservations', 'オーナー', 21, 1),
       ('reservations', 'オーナーID', 22, 1),
       ('reservations', 'オーナーEmail', 23, 1),
       ('reservations', '利用予定日', 24, 1),
       ('reservations', '予約完了日時', 25, 1),
       ('reservations', 'キャンセル日時', 26, 1),
       ('reservations', 'ステータス', 27, 1),
       ('reservations', 'PR枠経由', 28, 1),
       ('reservations', 'トラッキングリンク', 29, 1),
       ('reservations', 'キャンセルの原因', 30, 1),
       ('reservations', 'キャンセル理由', 31, 1),
       ('reservations', '否認理由', 32, 1),
       ('reservations', '取り消し理由', 33, 1),
       ('reservations', 'スペース料金(税込)（税抜）', 34, 1),
       ('reservations', 'スペース料金(税込)（税込）', 35, 1),
       ('reservations', 'クーポン ID', 36, 1),
       ('reservations', '割引率', 37, 1),
       ('reservations', 'クーポン割引金額（税抜）', 38, 1),
       ('reservations', 'クーポン割引金額（税込）', 39, 1),
       ('reservations', 'スペース利用料（税抜）', 40, 1),
       ('reservations', 'スペース利用料（税込）', 41, 1),
       ('reservations', '成約手数料（税抜）', 42, 1),
       ('reservations', '成約手数料（税込）', 43, 1),
       ('reservations', '成約手数料率', 44, 1),
       ('reservations', 'クレカ決済手数料（税抜）', 45, 1),
       ('reservations', 'クレカ決済手数料（税込）', 46, 1),
       ('reservations', 'オーナー様の売上（税抜）', 47, 1),
       ('reservations', 'オーナー様の売上（税込）', 48, 1),
       ('reservations', 'ピザ等のデリバリー', 49, 1),
       ('reservations', 'ケータリング', 50, 1),
       ('reservations', '出張シェフ', 51, 1),
       ('reservations', '記念日のケーキ', 52, 1),
       ('reservations', '飲み物（アルコールを含む）', 53, 1),
       ('reservations', '360度カメラレンタル', 54, 1),
       ('reservations', 'チェキレンタル', 55, 1),
       ('reservations', 'プロジェクターレンタル', 56, 1),
       ('reservations', 'スピーカーレンタル', 57, 1),
       ('reservations', 'パーティー用の飾り付けなどの備品', 58, 1),
       ('reservations', 'ネットで予約ができる', 59, 1),
       ('reservations', '電話で予約ができる', 60, 1),
       ('reservations', 'コンシェルジュに相談ができる', 61, 1),
       ('reservations', 'ネット予約でクーポンが使える', 62, 1),
       ('reservations', '直前割引が使えるスペースがある', 63, 1),
       ('reservations', '他社よりもスペースの値段が安い', 64, 1),
       ('reservations', '現金で決済できる', 65, 1),
       ('reservations', '会員なので予約情報入力が簡単', 66, 1),
       ('reservations', '友達紹介キャンペーンがある', 67, 1),
       ('reservations', '上記以外', 68, 1),
       ('reservations', 'トラッキングリンク（オーナー）',69,1),
       ('reservations', '利用時間',70,1),
       ('reservations', '利用者区分',71,1),
       ('reservations', 'クーポン名',72,1),
       ('reservations', 'クーポンコード',73,1),
       ('reservations', '予約種別',74,1),
       ('reservations', '特別割引(税別)',75,1),
       ('reservations', '特別割引(税込)',76,1),
       ('reservations', '代理予約種別',77,1),
       ('reservations', 'その他の利用目的',78,1);
