INSERT INTO `postal_code_prefecture_eav`(`id`,`namespace`,`attribute`,`value`,`type`) VALUES 
( '1', '1', 'name__ja', '北海道', 's' ),
( '2', '1', 'name__en', 'HOKKAIDO', 's' ),
( '3', '2', 'name__ja', '青森県', 's' ),
( '4', '2', 'name__en', 'AOMORI KEN', 's' ),
( '5', '3', 'name__ja', '岩手県', 's' ),
( '6', '3', 'name__en', 'IWATE KEN', 's' ),
( '7', '4', 'name__ja', '宮城県', 's' ),
( '8', '4', 'name__en', 'MIYAGI KEN', 's' ),
( '9', '5', 'name__ja', '秋田県', 's' ),
( '10', '5', 'name__en', 'AKITA KEN', 's' ),
( '11', '6', 'name__ja', '山形県', 's' ),
( '12', '6', 'name__en', 'YAMAGATA KEN', 's' ),
( '13', '7', 'name__ja', '福島県', 's' ),
( '14', '7', 'name__en', 'FUKUSHIMA KEN', 's' ),
( '15', '8', 'name__ja', '茨城県', 's' ),
( '16', '8', 'name__en', 'IBARAKI KEN', 's' ),
( '17', '9', 'name__ja', '栃木県', 's' ),
( '18', '9', 'name__en', 'TOCHIGI KEN', 's' ),
( '19', '10', 'name__ja', '群馬県', 's' ),
( '20', '10', 'name__en', 'GUMMA KEN', 's' ),
( '21', '11', 'name__ja', '埼玉県', 's' ),
( '22', '11', 'name__en', 'SAITAMA KEN', 's' ),
( '23', '12', 'name__ja', '千葉県', 's' ),
( '24', '12', 'name__en', 'CHIBA KEN', 's' ),
( '25', '13', 'name__ja', '東京都', 's' ),
( '26', '13', 'name__en', 'TOKYO TO', 's' ),
( '27', '14', 'name__ja', '神奈川県', 's' ),
( '28', '14', 'name__en', 'KANAGAWA KEN', 's' ),
( '29', '15', 'name__ja', '新潟県', 's' ),
( '30', '15', 'name__en', 'NIIGATA KEN', 's' ),
( '31', '16', 'name__ja', '富山県', 's' ),
( '32', '16', 'name__en', 'TOYAMA KEN', 's' ),
( '33', '17', 'name__ja', '石川県', 's' ),
( '34', '17', 'name__en', 'ISHIKAWA KEN', 's' ),
( '35', '18', 'name__ja', '福井県', 's' ),
( '36', '18', 'name__en', 'FUKUI KEN', 's' ),
( '37', '19', 'name__ja', '山梨県', 's' ),
( '38', '19', 'name__en', 'YAMANASHI KEN', 's' ),
( '39', '20', 'name__ja', '長野県', 's' ),
( '40', '20', 'name__en', 'NAGANO KEN', 's' ),
( '41', '21', 'name__ja', '岐阜県', 's' ),
( '42', '21', 'name__en', 'GIFU KEN', 's' ),
( '43', '22', 'name__ja', '静岡県', 's' ),
( '44', '22', 'name__en', 'SHIZUOKA KEN', 's' ),
( '45', '23', 'name__ja', '愛知県', 's' ),
( '46', '23', 'name__en', 'AICHI KEN', 's' ),
( '47', '24', 'name__ja', '三重県', 's' ),
( '48', '24', 'name__en', 'MIE KEN', 's' ),
( '49', '25', 'name__ja', '滋賀県', 's' ),
( '50', '25', 'name__en', 'SHIGA KEN', 's' ),
( '51', '26', 'name__ja', '京都府', 's' ),
( '52', '26', 'name__en', 'KYOTO FU', 's' ),
( '53', '27', 'name__ja', '大阪府', 's' ),
( '54', '27', 'name__en', 'OSAKA FU', 's' ),
( '55', '28', 'name__ja', '兵庫県', 's' ),
( '56', '28', 'name__en', 'HYOGO KEN', 's' ),
( '57', '29', 'name__ja', '奈良県', 's' ),
( '58', '29', 'name__en', 'NARA KEN', 's' ),
( '59', '30', 'name__ja', '和歌山県', 's' ),
( '60', '30', 'name__en', 'WAKAYAMA KEN', 's' ),
( '61', '31', 'name__ja', '鳥取県', 's' ),
( '62', '31', 'name__en', 'TOTTORI KEN', 's' ),
( '63', '32', 'name__ja', '島根県', 's' ),
( '64', '32', 'name__en', 'SHIMANE KEN', 's' ),
( '65', '33', 'name__ja', '岡山県', 's' ),
( '66', '33', 'name__en', 'OKAYAMA KEN', 's' ),
( '67', '34', 'name__ja', '広島県', 's' ),
( '68', '34', 'name__en', 'HIROSHIMA KEN', 's' ),
( '69', '35', 'name__ja', '山口県', 's' ),
( '70', '35', 'name__en', 'YAMAGUCHI KEN', 's' ),
( '71', '36', 'name__ja', '徳島県', 's' ),
( '72', '36', 'name__en', 'TOKUSHIMA KEN', 's' ),
( '73', '37', 'name__ja', '香川県', 's' ),
( '74', '37', 'name__en', 'KAGAWA KEN', 's' ),
( '75', '38', 'name__ja', '愛媛県', 's' ),
( '76', '38', 'name__en', 'EHIME KEN', 's' ),
( '77', '39', 'name__ja', '高知県', 's' ),
( '78', '39', 'name__en', 'KOCHI KEN', 's' ),
( '79', '40', 'name__ja', '福岡県', 's' ),
( '80', '40', 'name__en', 'FUKUOKA KEN', 's' ),
( '81', '41', 'name__ja', '佐賀県', 's' ),
( '82', '41', 'name__en', 'SAGA KEN', 's' ),
( '83', '42', 'name__ja', '長崎県', 's' ),
( '84', '42', 'name__en', 'NAGASAKI KEN', 's' ),
( '85', '43', 'name__ja', '熊本県', 's' ),
( '86', '43', 'name__en', 'KUMAMOTO KEN', 's' ),
( '87', '44', 'name__ja', '大分県', 's' ),
( '88', '44', 'name__en', 'OITA KEN', 's' ),
( '89', '45', 'name__ja', '宮崎県', 's' ),
( '90', '45', 'name__en', 'MIYAZAKI KEN', 's' ),
( '91', '46', 'name__ja', '鹿児島県', 's' ),
( '92', '46', 'name__en', 'KAGOSHIMA KEN', 's' ),
( '93', '47', 'name__ja', '沖縄県', 's' ),
( '94', '47', 'name__en', 'OKINAWA KEN', 's' );

